#!/bin/bash
while : ; do
  if [[ ! -e /tmp/lockfile1 ]]; then
    touch /tmp/lockfile1
    /usr/bin/scaberryup.bin
  fi
  clear;
  sleep 5
  sudo rm /tmp/lockfile1
  echo "Ate Logo!! ScadaBerry"
  sleep 5
  sudo init 6
  clear;
done
